Cleanup Documentation
bitrise-steplib/steps-xcode-build-for-simulator pull request #35
Opened 2022-05-26 17:18 UTC by hisaac

### Checklist

- [x] I've read and followed the [Contribution Guidelines](https://github.com/bitrise-steplib/.github/blob/main/CONTRIBUTING.md)
- [x] `step.yml` and `README.md` is updated with the changes (if needed)

### Version

Requires a *MAJOR/MINOR/PATCH* [version update](https://semver.org/)

### Context

This change just updates the documentation in the `step.yml` file to better match our determined style.

### Changes

- Added `.vscode` to the `.gitignore`
- Slimmed down the step's description to only include mention of commonly modified inputs, rather than descriptions of every input.
- Updated some input titles and descriptions.

### Investigation details

I met with a member of the tech writers team to learn more about how best to document steps, and will have them review this PR prior to opening it.

2022-05-31 11:04 UTC, zoltan-baba requested changes

2022-05-31 11:04 UTC, zoltan-baba commented on step.yml
> +      title: Scheme Name
name

2022-05-31 11:04 UTC, zoltan-baba commented on step.yml
> +      title: Device Model
model

2022-05-31 11:04 UTC, zoltan-baba commented on step.yml
> +      title: OS Version
version

2022-05-31 11:04 UTC, zoltan-baba commented on step.yml
> +      title: "Configuration Name"
name

2022-05-31 11:04 UTC, zoltan-baba commented on step.yml
> +      title: Disable Indexing During the Build
Disable indexing during the build

2022-05-31 11:04 UTC, zoltan-baba commented on step.yml
> +      title: Enable Caching of Swift Package Manager Packages
Enable caching of Swift Package Manager packages

2022-05-31 11:04 UTC, zoltan-baba commented on step.yml
> +      title: Additional `xcodebuild` Options
options

2022-05-31 11:04 UTC, zoltan-baba commented on step.yml
> +      title: Do a Clean Xcode Build Before the Build?
Do a clean Xcode build before the build?

2022-05-31 11:04 UTC, zoltan-baba commented on step.yml
> +      title: Verbose Logging
logging

2022-05-31 11:04 UTC, zoltan-baba commented on step.yml
> +      title: List of the Generated App Paths
generated app paths

2022-05-31 11:04 UTC, zoltan-baba commented on step.yml
> +      title: Full Raw Build Output File Path
```suggestion
      title: Full raw build output filepath
```

2022-05-31 12:58 UTC, hisaac commented
Thanks for all the good suggestions @zoltan-baba! I believe I've addressed them all in https://github.com/bitrise-steplib/steps-xcode-build-for-simulator/pull/35/commits/aab926a0ff96f00f7561305ceec68ad360bb0edb. Let me know if you see anything else.

2022-06-02 12:56 UTC, zoltan-baba submitted a review, later dismissed

2022-06-02 14:51 UTC, hisaac commented
@ofalvai I've updated the input title/summary/description info to match the conventions you sent me in https://github.com/bitrise-steplib/steps-xcode-build-for-simulator/pull/35/commits/6bf397c8663023c50732594cf07d368bac19df25 👍

2022-06-02 16:05 UTC, ofalvai approved these changes

2022-06-02 16:29 UTC, merged